#!/usr/bin/env python3
"""Generate Core/Inc/net_auto_config.h from .config (via Kconfig)."""

import os, sys

SRC_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT    = os.path.dirname(SRC_DIR)
HEADER  = os.path.join(ROOT, "Core", "Inc", "net_auto_config.h")
KCONFIG = os.path.join(ROOT, "Kconfig")
DOTCONF = os.path.join(ROOT, ".config")

try:
    import kconfiglib
except ImportError:
    print("kconfiglib not found. Install: pip install kconfiglib", file=sys.stderr)
    sys.exit(1)

def main():
    kconf = kconfiglib.Kconfig(KCONFIG)

    if os.path.exists(DOTCONF):
        kconf.load_config(DOTCONF, replace=False)

    defines = []

    def cfg(name, typ="string"):
        sym = kconf.syms.get(name)
        if sym is None:
            print(f"WARNING: symbol {name} not found", file=sys.stderr)
            return
        if typ == "bool":
            defines.append(f'#define {name}     {1 if sym.tri_value == 2 else 0}')
            return
        val = sym.str_value
        if sym.user_value is None:
            for d, _ in sym.defaults:
                val = d.str_value
                break
        if typ == "string":
            defines.append(f'#define {name}     "{val}"')
        else:
            defines.append(f'#define {name}     {val}')

    cfg("AUTO_WIFI_ENABLE",     "bool")
    cfg("AUTO_WIFI_SSID",       "string")
    cfg("AUTO_WIFI_PWD",        "string")
    cfg("AUTO_TIMEOUT_WIFI",    "int")

    cfg("AUTO_MQTT_ENABLE",     "bool")
    cfg("AUTO_MQTT_IP",         "string")
    cfg("AUTO_MQTT_PORT",       "string")
    cfg("AUTO_MQTT_CLIENT",     "string")
    cfg("AUTO_TIMEOUT_MQTT",    "int")

    cfg("AUTO_SUB_ENABLE",      "bool")
    cfg("AUTO_SUB_TOPIC",       "string")
    cfg("AUTO_TIMEOUT_SUB",     "int")

    cfg("AUTO_PUB_ENABLE",      "bool")
    cfg("AUTOPUB_INTERVAL_S",   "int")

    cfg("AUTO_SUB_ECHO",        "bool")

    header = """/*
 * net_auto_config.h — generated by Config/gen_header.py from .config
 * DO NOT EDIT BY HAND — use 'make menuconfig' instead.
 */
#ifndef __NET_AUTO_CONFIG_H__
#define __NET_AUTO_CONFIG_H__

""" + "\n".join(defines) + """

#endif /* __NET_AUTO_CONFIG_H__ */
"""
    with open(HEADER, "w") as f:
        f.write(header)
    print(f"Generated: {HEADER}")

if __name__ == "__main__":
    main()
