/*
 * net_auto_config.h — generated by Config/gen_header.py from .config
 * DO NOT EDIT BY HAND — use 'make menuconfig' instead.
 */
#ifndef __NET_AUTO_CONFIG_H__
#define __NET_AUTO_CONFIG_H__

#define AUTO_WIFI_ENABLE     0
#define AUTO_WIFI_SSID     ""
#define AUTO_WIFI_PWD     ""
#define AUTO_TIMEOUT_WIFI     25000
#define AUTO_MQTT_ENABLE     0
#define AUTO_MQTT_IP     ""
#define AUTO_MQTT_PORT     "1883"
#define AUTO_MQTT_CLIENT     ""
#define AUTO_TIMEOUT_MQTT     15000
#define AUTO_SUB_ENABLE     0
#define AUTO_SUB_TOPIC     ""
#define AUTO_TIMEOUT_SUB     10000
#define AUTO_PUB_ENABLE     0
#define AUTOPUB_INTERVAL_S     5

#endif /* __NET_AUTO_CONFIG_H__ */
